import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';

/**
 * Lint for the things a reader trips over, not for style.
 *
 * Formatting is not in here. Arguing about semicolons in review costs more
 * attention than it saves, and TypeScript already refuses the errors that
 * actually break things: `strict`, `noUncheckedIndexedAccess` and
 * `exactOptionalPropertyTypes` are all on, so a whole class of rules other
 * projects need is unnecessary here.
 *
 * What is left is the set that catches a reader out. A promise nobody waited
 * for, a condition that is always true, an `any` that quietly turns off the
 * type system a few files away from where it was written. Those are the
 * defects that survive review because they look fine.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      'examples/**',
      'evals/**',
      // Regenerated by Next on every build, and it says so in the file.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        /*
         * A project that includes the tests.
         *
         * The build config excludes them so they never reach dist, which also
         * meant the linter could not parse them and reported thirty-seven
         * files as errors. The tests are the part most worth linting: they are
         * where a floating promise hides best.
         */
        project: [
          './tsconfig.eslint.json',
          './frontend/tsconfig.eslint.json',
          './driftmart/tsconfig.eslint.json',
        ],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      /*
       * A floating promise is the bug that looks like working code.
       *
       * Every one is work nobody is waiting for, which on a pipeline that
       * writes to a store means an ordering nobody chose. `void` in front says
       * the omission was deliberate.
       */
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',

      /*
       * `any` is contagious. It disables checking wherever the value lands,
       * which is usually not the file it was written in.
       */
      '@typescript-eslint/no-explicit-any': 'error',

      /*
       * The `unsafe-*` family is off, and that is a decision rather than an
       * oversight.
       *
       * This codebase reads JSON from Bright Data, from its own store and from
       * the browser, and narrows every one of those from `unknown` at the
       * boundary. That is the careful version, and it is exactly what those
       * rules fire on. Leaving them on produced a thousand warnings against
       * the pattern we want, which trains a reader to ignore the linter.
       *
       * What stops a bad value getting through here is the type system, which
       * runs with `strict`, `noUncheckedIndexedAccess` and
       * `exactOptionalPropertyTypes`, plus a zod schema at every external
       * edge.
       */

      // Silent coercion in a template is how "[object Object]" reaches a page.
      '@typescript-eslint/no-base-to-string': 'error',
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: true },
      ],

      // Dead code, and assertions that assert nothing.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',

      // Invisible characters and stray escapes, which read as noise and
      // occasionally as a bug nobody can see.
      'no-irregular-whitespace': 'error',
      'no-useless-escape': 'error',

      // Off: `unknown` narrowing at boundaries, see above.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      // Off: an async function with no await is a signature choice, not a bug.
      '@typescript-eslint/require-await': 'off',
      // Warn only: often correct, and noisy against defensive checks on data
      // that is typed more precisely than it arrives.
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
    },
  },

  {
    /*
     * Tests get more rope, deliberately.
     *
     * A test builds broken and half-formed values on purpose, which is exactly
     * what the unsafe-* rules are there to stop in production code. Enforcing
     * them here would push authors towards tidy fixtures, and a tidy fixture
     * is one that never reproduces the bug.
     */
    files: ['**/*.test.ts', '**/*.test.tsx', '**/scripts/**'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    /*
     * Config files are plain JavaScript and are not in any tsconfig, so the
     * type-aware rules have no program to consult and the parser errors out.
     * They still get the syntax and correctness rules from js.configs.
     */
    files: ['**/*.mjs', '**/*.js', '**/*.cjs'],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      // Spread after disableTypeChecked, which carries a languageOptions of
      // its own and silently replaces this one if it comes second.
      ...tseslint.configs.disableTypeChecked.languageOptions,
      globals: globals.node,
    },
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      // These files run on Node, where require() is the point.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    /*
     * Next's own rules, on the Next app only.
     *
     * These catch the framework mistakes types cannot see: a raw <img> where
     * next/image belongs, a plain <a> for internal navigation, a sync script in
     * the document. Nothing here overlaps with the rules above.
     */
    files: ['frontend/**/*.{ts,tsx}', 'driftmart/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // Looks for a pages/ directory. This is an app router project and
      // does not have one, so the rule only ever prints its own warning.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
);
